### ISSUE TITLE
Inaccurate Tuning ROC Curve generated at end of tuning

### ISSUE THREAD

**Issue by dvitale199** [GenoML/genoml_v2#3]
<em>Please make sure that this is a bug.</em>

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): RHEL 7.8 (biowulf)
- GenoML installed from (source or binary): Source
- GenoML version: python_v1.5
- Python version: 3.7

**Describe the current behavior**

Currently, a ROC curve is being generated for Tuning. Tuning ROC is, by design going to be pushed up to 1.0 because it is generated on training samples and is thus, not a useful output
<img width="959" alt="Screen Shot 2020-04-30 at 10 49 25 AM" src="https://user-images.githubusercontent.com/24816003/80814019-1f52d200-8b99-11ea-87a0-fb0d070676bc.png">

**Describe the expected behavior**
tuning should output table of mean, sd, min, and max for cv

**Code to reproduce the issue**
Run tuning and view output ROC curve

**Other info / logs**
None

**Comment by m-makarious** [comment]
Moved issue to new repo for completeness and consistency
