### ISSUE TITLE
requirements.txt should include package version info

### ISSUE THREAD

**Issue by mgibbs1259** [GenoML/genoml_v2#4]
<em>Please make sure that this is a feature request.</em>

**System information**
- GenoML version (you are using): 1.5
- Are you willing to contribute it (Yes/No): Yes

**Describe the feature and the current behavior/state.**
To avoid ending up in dependency hell, the requirements.txt file should include package versions. 

**Will this change the current api? How?**
No

**Who will benefit with this feature?**
Everyone! This will help ensure reproducibility. 

**Any Other info.**

**Comment by m-makarious** [comment]
Moved issue to new repo for completeness and consistency
