### ISSUE TITLE
Interesting people put non-variant columns into ML experiments???

### ISSUE THREAD

**Issue by mikeDTI** [GenoML/genoml_v2#5]
<em>Please make sure that this is a bug.</em>

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):
Ubuntu 18.04

- GenoML installed from (source or binary):
Source

- GenoML version:
1.5!

- Python version:
3.7, only real G's use that one

**Describe the current behavior**
Will crash at Z scoring feature w/o variance

**Describe the expected behavior**
Interesting people put non-variant columns into ML experiments???
Mary is going to put an extra condition at line 210 of munge that skips columns with standard deviations of 0 and leaves a snarky message ;-)

**Code to reproduce the issue**
AMP PD transcriptomics

**Other info / logs**
Ask MM

**Comment by m-makarious** [comment]
Moved issue to new repo for completeness and consistency
