### ISSUE TITLE
Feature Request: skip SNP pruning.

### ISSUE THREAD

**Issue by mikeDTI** [GenoML/genoml_v2#6]
<em>Please make sure that this is a feature request.</em>

**System information**
- GenoML version (you are using): 1.5
- Are you willing to contribute it (Yes/No): Maybe

**Describe the feature and the current behavior/state.** Everything is great but maybe we should include a CLI option to skip SNP pruning. You could see how this would be important for investigating a single genomic region in detail.

**Will this change the current api? How?** One more CLI option in munge.

**Who will benefit with this feature?** People interested in granular / preselected genetic features.

**Any Other info.** You are cool dudes.

**Comment by m-makarious** [comment]
Moved issue to new repo for completeness and consistency
